### PR TITLE
Update lint version to 25.2.0

### PR DESCRIPTION
**Pull request by dcow**
This is the latest version of lint on both mavenCentral and jcenter.

### CODE REVIEW

**Comment by dcow** [comment]
https://code.google.com/p/android/issues/detail?id=220168

**Comment by blakearnold** [comment]
Thanks for your PR!
I actually have an open PR for a lint upgrade here https://github.com/SonarQubeCommunity/sonar-android/pull/22.
It's actually more complicated to upgrade due to breaking API changes.

I've been meaning to get back to it for submission. Hopefully I'll have some time soon to finish it.

**Comment by dcow** [comment]
@blakearnold yeah I can't test anything yet because the dependencies are missing per the issue I linked. I saw your pr to upgrade go 25.1.2 or so. I figured I'd submit one for 25.2.0 and rebase once yours is merged.

**Comment by rompic** [comment]
any news on this one?

**Pull request closed without merging**
